/* SKALA Ops Desk: an anonymous daily learning operating system, not a feed. */
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, CheckCircle2, CircleDashed, Clock3, CornerDownRight, HandHeart, Layers3, MessageCircleMore, MoreHorizontal, Plus, Send, Sparkles, UsersRound, X } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";

type Mode = "강의 끝" | "과제 중" | "팀 작업";
type Action = { id: string; title: string; note: string; minutes: string; kind: "now" | "resume" | "close" };
type Relay = { id: number; mode: Mode; course: string; ask: string; tried: string; need: string; state: "도움 필요" | "힌트 도착" | "다시 해보는 중"; example?: boolean };

const actionBank: Record<Mode, { course: string; phase: string; actions: Action[]; question: string }> = {
  "강의 끝": { course: "Java, SpringBoot, Rest API 구현", phase: "구축 구간 · API 실습", question: "방금 들었는데, 이제 뭘 먼저 해보지?", actions: [{ id: "a1", title: "오늘 예제를 내 손으로 한 번만 다시 치기", note: "코드 안 보고, 막히는 줄만 체크", minutes: "15분", kind: "now" }, { id: "a2", title: "응답이 안 보이는 이유 하나만 좁히기", note: "요청 → 컨트롤러 → 화면 순서로", minutes: "10분", kind: "now" }, { id: "a3", title: "다음 수업 전까지 남길 질문 한 줄 적기", note: "완벽하게 정리하지 않아도 됨", minutes: "2분", kind: "close" }] },
  "과제 중": { course: "웹 서비스 개발 mini-Project", phase: "배포 구간 · 미니프로젝트", question: "제출은 해야 하는데, 이게 맞나 싶어.", actions: [{ id: "b1", title: "오늘 반드시 되는 범위를 한 줄로 자르기", note: "예: 로그인 말고 목록 조회까지만", minutes: "5분", kind: "now" }, { id: "b2", title: "막힌 지점에 필요한 도움만 요청하기", note: "정답 말고 확인 순서만", minutes: "3분", kind: "now" }, { id: "b3", title: "되는 화면 하나를 남겨두기", note: "내일 다시 시작할 곳 만들기", minutes: "5분", kind: "resume" }] },
  "팀 작업": { course: "팀프로젝트", phase: "프로젝트 구간 · 합의와 구현", question: "지금 코드보다 결정을 먼저 해야 할 것 같아.", actions: [{ id: "c1", title: "서로 다른 선택지 두 개만 적기", note: "누가 맞는지보다 뭐가 다른지", minutes: "8분", kind: "now" }, { id: "c2", title: "오늘 합의할 한 가지를 정하기", note: "폴더 구조 전체 말고, 이번 기능 기준", minutes: "5분", kind: "now" }, { id: "c3", title: "결정한 이유를 한 줄로 남기기", note: "다음 회의에서 다시 헤매지 않게", minutes: "2분", kind: "close" }] },
};

const starterRelays: Relay[] = [
  { id: 1, mode: "강의 끝", course: "Java, SpringBoot, Rest API 구현", ask: "응답은 오는데 화면은 그대로예요. 어디부터 다시 볼까요?", tried: "컨트롤러까지 들어오는 건 확인했어요.", need: "확인 순서 하나만", state: "도움 필요", example: true },
  { id: 2, mode: "과제 중", course: "웹 서비스 개발 mini-Project", ask: "로그인까지 하려다 시간이 다 갈 것 같아요. 범위를 어디서 자를까요?", tried: "목록 조회 화면은 만들어뒀어요.", need: "우선순위 한 줄", state: "힌트 도착", example: true },
  { id: 3, mode: "팀 작업", course: "팀프로젝트", ask: "폴더 구조를 지금 정할지, 기능 먼저 갈지 의견이 갈렸어요.", tried: "두 안을 간단히 적어놓았어요.", need: "결정 기준 하나", state: "다시 해보는 중", example: true },
];

export default function Home() {
  const [mode, setMode] = useState<Mode>("강의 끝"); const [done, setDone] = useState<string[]>([]); const [relays, setRelays] = useState<Relay[]>(starterRelays); const [composer, setComposer] = useState(false); const [detail, setDetail] = useState<Relay | null>(null); const [ask, setAsk] = useState(""); const [tried, setTried] = useState(""); const [need, setNeed] = useState("확인 순서 하나만"); const [hint, setHint] = useState(""); const [notice, setNotice] = useState("");
  const current = actionBank[mode]; const actions = current.actions; const modeRelays = useMemo(() => relays.filter((relay) => relay.mode === mode), [relays, mode]);
  useEffect(() => { try { setDone(JSON.parse(localStorage.getItem("skala-ops-done") || "[]")); } catch { setDone([]); } }, []); useEffect(() => { localStorage.setItem("skala-ops-done", JSON.stringify(done)); }, [done]);
  const ping = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(""), 2600); };
  function toggleAction(id: string) { setDone((currentDone) => currentDone.includes(id) ? currentDone.filter((item) => item !== id) : [...currentDone, id]); }
  function sendRelay() { if (!ask.trim()) return ping("지금 막힌 장면을 한 줄로만 적어주세요."); const relay: Relay = { id: Date.now(), mode, course: current.course, ask, tried: tried || "아직 해본 건 없어요. 어디서 시작할지 모르겠어요.", need, state: "도움 필요" }; setRelays((currentRelays) => [relay, ...currentRelays]); setComposer(false); setAsk(""); setTried(""); ping("좋아요. 같은 일을 하고 있는 사람에게 먼저 보여줄게요."); }
  function sendHint() { if (!detail || !hint.trim()) return ping("정답 말고, 한 번 더 해볼 수 있는 힌트만 적어주세요."); const update = { ...detail, state: "힌트 도착" as const }; setRelays((currentRelays) => currentRelays.map((relay) => relay.id === update.id ? update : relay)); setDetail(update); setHint(""); ping("좋아요. 상대가 다시 손을 움직일 수 있겠네요."); }
  function resumeRelay(id: number) { setRelays((currentRelays) => currentRelays.map((relay) => relay.id === id ? { ...relay, state: "다시 해보는 중" } : relay)); setDetail(null); ping("좋아요. 다음 한 번 해보고, 안 되면 다시 와도 돼요."); }
  return <div className="ops-app"><aside className="ops-rail"><div className="ops-mark"><i /><i /><b /></div><span>SKALA<br />OPS<br />DESK</span><small>오늘의<br />다음 한 번</small></aside><main>
    <header className="ops-header"><div className="ops-brand">막힘<span>↳</span>교환소 <small>LEARNING OPS</small></div><div className="header-right"><p><CircleDashed size={14} /> 로그인 없이 쌓이는 오늘의 기록</p><button onClick={() => setComposer(true)}><Plus size={15} /> 도움 요청</button></div></header>
    <section className="ops-hero"><div className="hero-ruler"><span>NOW</span><strong>01<br />DAY</strong></div><div className="hero-body"><p className="eyebrow">{mode} · 지금 이 순간에 제일 많이 나오는 말</p><h1><em>다음 한 번</em>을<br />정하면 돼요.</h1><p>잘하려고 멈춘 게 아니라, 어디부터 할지 몰라 멈춘 거예요.<br />지금 할 한 가지만 작게 잡아봅시다.</p><div className="mode-switch">{(Object.keys(actionBank) as Mode[]).map((item, index) => <button key={item} className={mode === item ? "active" : ""} onClick={() => setMode(item)}><span>0{index + 1}</span>{item}</button>)}</div></div><div className="hero-evidence"><img src="/manus-storage/quiet-signal-archive-evidence_91b27012.png" alt="막힌 학습의 주석 기록" /><div><span>오늘의 맥락</span><strong>{current.course}</strong><small>{current.phase}</small></div><div className="live-record"><span>LIVE RELAY · 막힘 단계 / {modeRelays[0]?.state ?? "도움 필요"}</span><strong>{modeRelays[0]?.ask ?? "여기서 먼저 멈춘 사람이 없어요."}</strong><small>힌트 유형 / {modeRelays[0]?.need ?? "확인 순서 하나만"}</small></div></div></section>
    <section className="ops-workspace"><div className="next-panel"><div className="panel-kicker"><span>WHAT NOW</span><p>{current.phase}</p></div><h2>{current.question}</h2><p className="panel-intro">지금 필요한 건 의지나 계획표가 아니라, <strong>다음 15분을 쓸 곳</strong>이에요.</p><div className="action-list">{actions.map((action, index) => <button key={action.id} className={done.includes(action.id) ? "done" : ""} onClick={() => toggleAction(action.id)}><span className="action-check">{done.includes(action.id) ? <Check size={14} /> : `0${index + 1}`}</span><div><strong>{action.title}</strong><small>{action.note}</small></div><em>{action.minutes}</em></button>)}</div><div className="progress-line"><i style={{ width: `${(actions.filter((action) => done.includes(action.id)).length / actions.length) * 100}%` }} /><span>{actions.filter((action) => done.includes(action.id)).length}/{actions.length} 오늘 해둔 것</span></div></div>
      <aside className="relay-panel"><div className="panel-kicker"><span>HELP RELAY</span><p>같은 상황의 사람</p></div><h2>딱 1분만<br />빌려줄래요?</h2><p className="relay-intro">정답이 없어도 돼요. “저는 여기부터 봤어요” 한 줄이면 됩니다.</p><div className="relay-list">{modeRelays.map((relay) => <button key={relay.id} onClick={() => setDetail(relay)}><span className={`relay-state ${relay.state}`}>{relay.state}</span><strong>{relay.ask}</strong><small>{relay.need} <ArrowRight size={13} /></small></button>)}</div><button className="ask-link" onClick={() => setComposer(true)}>나도 여기서 막혔어요 <Plus size={14} /></button></aside></section>
    <section className="ops-log"><div className="log-title"><p>RESTART QUEUE</p><h2>오늘 멈춘 곳은,<br /><em>내일 다시 시작할 곳.</em></h2></div><div className="log-steps"><article><span>01</span><div><p>지금 할 일</p><strong>강의나 작업의 흐름이 끊기기 전에 다음 한 번을 정합니다.</strong></div></article><article><span>02</span><div><p>막히면</p><strong>질문을 잘 쓰려고 하지 말고, 어디에서 멈췄는지만 남깁니다.</strong></div></article><article><span>03</span><div><p>다시 시작</p><strong>내일 열었을 때 바로 손이 움직일 수 있게 한 줄을 남겨둡니다.</strong></div></article></div></section>
    <footer>막힘 교환소는 답을 모아두는 곳이 아니라, <strong>다음 한 번을 서로 만들어주는 곳</strong>입니다.</footer>
  </main>
  {composer && <div className="overlay"><div className="request-modal"><button className="close" onClick={() => setComposer(false)}><X size={18} /></button><p>지금은 <strong>{mode}</strong> · {current.course}</p><h2>어디에서 멈췄어요?</h2><span>정리 안 돼도 괜찮아요. 같은 걸 하고 있는 사람한테 짧게 물어보면 됩니다.</span><input autoFocus value={ask} onChange={(event) => setAsk(event.target.value)} placeholder="예: 요청은 성공인데 화면이 안 바뀌어요" /><Textarea value={tried} onChange={(event) => setTried(event.target.value)} placeholder="여기까지는 해봤어요. (비워도 돼요)" /><div className="need-chips">{["확인 순서 하나만", "범위 어디서 자를지", "결정 기준 하나", "같이 봐줄 사람"].map((item) => <button key={item} className={need === item ? "active" : ""} onClick={() => setNeed(item)}>{item}</button>)}</div><div className="modal-foot"><small>이름도, 반도, 닉네임도 안 물어봐요.</small><button onClick={sendRelay}>이거 좀 봐줄래요 <Send size={15} /></button></div></div></div>}
  {detail && <div className="overlay"><div className="detail-modal"><button className="close" onClick={() => setDetail(null)}><X size={18} /></button><div className="detail-top"><span>{detail.mode} · {detail.course}</span><b>{detail.state}</b></div><h2>{detail.ask}</h2><div className="tried-box"><p>여기까지는 해봤어요</p><strong>{detail.tried}</strong></div><div className="need-box"><HandHeart size={18} /><p>지금 필요한 건 <strong>{detail.need}</strong>이에요.</p></div><h3>지나가다 한마디만 남겨줄래요?</h3><div className="quick-hints"><button onClick={() => setHint("저는 여기부터 확인해봤어요: ")}>저는 여기부터 봤어요</button><button onClick={() => setHint("이건 한 번 확인해봤어요? ")}>이건 확인해봤어요?</button><button onClick={() => setHint("저는 여기서 이렇게 삽질했어요: ")}>저는 여기서 삽질했어요</button></div><Textarea value={hint} onChange={(event) => setHint(event.target.value)} placeholder="정답 말고, 다음 한 번만 알려주세요." /><div className="detail-foot"><button onClick={() => resumeRelay(detail.id)}><CheckCircle2 size={15} /> 오케이, 다시 해볼게요</button><button className="hint-send" onClick={sendHint}>힌트 보내기 <ArrowRight size={15} /></button></div></div></div>}
  {notice && <div className="notice"><Check size={15} /> {notice}</div>}
  </div>;
}
