/* SKALA Relay Feed: a dense anonymous request feed with browser-local UID and threaded replies. */
import { useEffect, useMemo, useState } from "react";
import { ArrowDownUp, ArrowRight, Check, CheckCircle2, ChevronDown, CircleDot, Filter, Flame, MessageCircleMore, Plus, Search, Send, UserRound, UsersRound, X } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";

type Mode = "강의 끝" | "과제 중" | "팀 작업";
type State = "도움 필요" | "힌트 도착" | "다시 해보는 중" | "해결 완료";
type FilterKey = "전체" | "도움 필요" | "힌트 도착" | "내 요청" | "내가 참여";
type SortKey = "최신순" | "댓글 많은 순" | "도움 필요 순";
type ThreadMessage = { id: string; uid: string; body: string; createdAt: string; parentId?: string };
type Relay = { id: number; ownerUid: string; mode: Mode; course: string; tag: string; ask: string; tried: string; need: string; state: State; createdAt: string; thread: ThreadMessage[]; sample?: boolean };

const sampleRelays: Relay[] = [
  { id: 109, ownerUid: "sample-a8", mode: "강의 끝", course: "Java, SpringBoot, Rest API 구현", tag: "API", ask: "응답은 오는데 화면은 그대로예요. 어디부터 다시 볼까요?", tried: "컨트롤러까지 들어오는 건 확인했어요.", need: "확인 순서 하나만", state: "도움 필요", createdAt: "방금", thread: [], sample: true },
  { id: 108, ownerUid: "sample-a7", mode: "과제 중", course: "웹 서비스 개발 mini-Project", tag: "기획", ask: "로그인까지 하려다 시간이 다 갈 것 같아요. 범위를 어디서 자를까요?", tried: "목록 조회 화면은 만들어뒀어요.", need: "우선순위 한 줄", state: "힌트 도착", createdAt: "3분 전", thread: [], sample: true },
  { id: 107, ownerUid: "sample-a6", mode: "팀 작업", course: "팀프로젝트", tag: "협업", ask: "폴더 구조를 지금 정할지, 기능 먼저 갈지 의견이 갈렸어요.", tried: "두 안을 간단히 적어놓았어요.", need: "결정 기준 하나", state: "다시 해보는 중", createdAt: "7분 전", thread: [], sample: true },
  { id: 106, ownerUid: "sample-a5", mode: "강의 끝", course: "Java, SpringBoot, Rest API 구현", tag: "JPA", ask: "엔티티 연관관계는 이해한 것 같은데 코드에서 바로 막혀요.", tried: "단방향부터 그려봤어요.", need: "처음 잡을 방향", state: "도움 필요", createdAt: "11분 전", thread: [], sample: true },
  { id: 105, ownerUid: "sample-a4", mode: "과제 중", course: "웹 서비스 개발 mini-Project", tag: "React", ask: "컴포넌트를 어디까지 쪼개야 하는지 감이 안 와요.", tried: "화면 단위로만 나눠봤어요.", need: "나누는 기준 하나", state: "힌트 도착", createdAt: "18분 전", thread: [], sample: true },
  { id: 104, ownerUid: "sample-a3", mode: "팀 작업", course: "팀프로젝트", tag: "Git", ask: "브랜치 이름부터 PR 순서까지 다 다르게 생각하고 있어요.", tried: "각자 방식은 적어봤어요.", need: "합의 시작점", state: "도움 필요", createdAt: "26분 전", thread: [], sample: true },
  { id: 103, ownerUid: "sample-a2", mode: "강의 끝", course: "RAG Pipeline 설계 및 구축", tag: "RAG", ask: "검색 결과는 있는데 답변이 왜 문서 밖으로 나갈까요?", tried: "top-k와 chunk 크기는 바꿔봤어요.", need: "확인할 값 하나", state: "다시 해보는 중", createdAt: "32분 전", thread: [], sample: true },
  { id: 102, ownerUid: "sample-a1", mode: "과제 중", course: "웹 서비스 개발 mini-Project", tag: "CSS", ask: "모바일에서만 레이아웃이 깨지는데 어디부터 봐야 할까요?", tried: "width를 줄여봤는데 더 깨졌어요.", need: "점검 순서", state: "도움 필요", createdAt: "41분 전", thread: [], sample: true },
  { id: 101, ownerUid: "sample-z9", mode: "팀 작업", course: "팀프로젝트", tag: "발표", ask: "데모에서 보여줄 흐름을 기능 목록 순서로 할지 고민이에요.", tried: "사용자 흐름을 적어봤어요.", need: "우선 보여줄 기준", state: "힌트 도착", createdAt: "1시간 전", thread: [], sample: true },
  { id: 100, ownerUid: "sample-z8", mode: "강의 끝", course: "SQL 기초", tag: "SQL", ask: "JOIN은 알겠는데 문제를 보면 어떤 테이블부터 봐야 할지 모르겠어요.", tried: "조건만 먼저 읽어봤어요.", need: "문제 읽는 순서", state: "도움 필요", createdAt: "1시간 전", thread: [], sample: true },
  { id: 99, ownerUid: "sample-z7", mode: "과제 중", course: "웹 서비스 개발 mini-Project", tag: "배포", ask: "환경변수는 넣었는데 배포 화면에서만 값이 비어 있어요.", tried: "로컬에서는 확인했어요.", need: "배포 전 점검", state: "다시 해보는 중", createdAt: "2시간 전", thread: [], sample: true },
  { id: 98, ownerUid: "sample-z6", mode: "팀 작업", course: "팀프로젝트", tag: "DB", ask: "테이블을 먼저 정하면 화면이 달라질까 봐 결정을 못 하겠어요.", tried: "필요한 데이터만 적어봤어요.", need: "결정의 기준", state: "도움 필요", createdAt: "2시간 전", thread: [], sample: true },
];
const uidLabel = (uid: string) => `익명 ${uid.slice(-4).toUpperCase()}`;
const makeUid = () => typeof crypto !== "undefined" && crypto.randomUUID ? `sk-${crypto.randomUUID().slice(0, 8)}` : `sk-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;

export default function Home() {
  const [relays, setRelays] = useState<Relay[]>(sampleRelays); const [uid, setUid] = useState(""); const [hydrated, setHydrated] = useState(false); const [filter, setFilter] = useState<FilterKey>("전체"); const [sort, setSort] = useState<SortKey>("최신순"); const [search, setSearch] = useState("");
  const [composer, setComposer] = useState(false); const [detail, setDetail] = useState<Relay | null>(null); const [mode, setMode] = useState<Mode>("강의 끝"); const [ask, setAsk] = useState(""); const [tried, setTried] = useState(""); const [need, setNeed] = useState("확인 순서 하나만"); const [reply, setReply] = useState(""); const [replyTo, setReplyTo] = useState<ThreadMessage | null>(null); const [notice, setNotice] = useState("");
  useEffect(() => { const savedUid = localStorage.getItem("skala-ops-anon-uid") || makeUid(); localStorage.setItem("skala-ops-anon-uid", savedUid); setUid(savedUid); try { const saved = JSON.parse(localStorage.getItem("skala-ops-relays") || "null"); if (Array.isArray(saved)) { const savedIds = new Set(saved.map((item: Relay) => item.id)); setRelays([...saved, ...sampleRelays.filter((item) => !savedIds.has(item.id))]); } } catch { /* initial samples stay visible */ } setHydrated(true); }, []);
  useEffect(() => { if (hydrated) localStorage.setItem("skala-ops-relays", JSON.stringify(relays)); }, [relays, hydrated]);
  useEffect(() => { const sync = (event: StorageEvent) => { if (event.key === "skala-ops-relays" && event.newValue) { try { const next = JSON.parse(event.newValue); if (Array.isArray(next)) setRelays(next); } catch { /* ignore invalid browser storage */ } } }; window.addEventListener("storage", sync); return () => window.removeEventListener("storage", sync); }, []);
  const ping = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(""), 2600); };
  const participated = (relay: Relay) => relay.ownerUid === uid || relay.thread.some((message) => message.uid === uid);
  const visibleRelays = useMemo(() => { const filtered = relays.filter((relay) => { const q = search.trim().toLowerCase(); const matchesSearch = !q || [relay.ask, relay.course, relay.tag, relay.need].join(" ").toLowerCase().includes(q); const matchesFilter = filter === "전체" || (filter === "도움 필요" && relay.state === "도움 필요") || (filter === "힌트 도착" && relay.state === "힌트 도착") || (filter === "내 요청" && relay.ownerUid === uid) || (filter === "내가 참여" && participated(relay)); return matchesSearch && matchesFilter; }); return [...filtered].sort((a, b) => sort === "댓글 많은 순" ? b.thread.length - a.thread.length : sort === "도움 필요 순" ? Number(b.state === "도움 필요") - Number(a.state === "도움 필요") || b.id - a.id : b.id - a.id); }, [relays, filter, sort, search, uid]);
  const mine = relays.filter((relay) => relay.ownerUid === uid); const joined = relays.filter((relay) => relay.ownerUid !== uid && relay.thread.some((message) => message.uid === uid)); const needCount = relays.filter((relay) => relay.state === "도움 필요").length;
  const updateDetail = (next: Relay) => { setRelays((items) => items.map((item) => item.id === next.id ? next : item)); setDetail(next); };
  function sendRelay() { if (!ask.trim()) return ping("막힌 장면을 한 줄로만 적어주세요."); if (!uid) return ping("익명 ID를 만드는 중이에요. 잠깐 뒤 다시 눌러주세요."); const item: Relay = { id: Date.now(), ownerUid: uid, mode, course: mode === "팀 작업" ? "팀프로젝트" : mode === "과제 중" ? "웹 서비스 개발 mini-Project" : "Java, SpringBoot, Rest API 구현", tag: mode === "팀 작업" ? "협업" : mode === "과제 중" ? "과제" : "수업", ask, tried: tried || "아직 해본 건 없어요. 어디서 시작할지 모르겠어요.", need, state: "도움 필요", createdAt: "방금", thread: [] }; setRelays((items) => [item, ...items]); setComposer(false); setAsk(""); setTried(""); setFilter("내 요청"); ping("요청을 올렸어요. 내 요청 필터에서 바로 다시 볼 수 있어요."); }
  function sendComment() { if (!detail || !reply.trim() || !uid) return ping("정답 말고, 다음 한 번을 해볼 수 있는 말만 남겨주세요."); const message: ThreadMessage = { id: `${Date.now()}-${uid}`, uid, body: reply.trim(), createdAt: "방금", ...(replyTo ? { parentId: replyTo.id } : {}) }; const next: Relay = { ...detail, state: detail.ownerUid === uid && !replyTo ? detail.state : "힌트 도착", thread: [...detail.thread, message] }; updateDetail(next); setReply(""); setReplyTo(null); ping(message.parentId ? "답글을 남겼어요." : "댓글을 남겼어요."); }
  function updateRequestState(state: State) { if (!detail || detail.ownerUid !== uid) return ping("요청자만 이 글의 상태를 바꿀 수 있어요."); updateDetail({ ...detail, state }); ping(state === "해결 완료" ? "해결 완료로 남겼어요. 고생했어요." : "다시 해보는 중으로 바꿨어요."); }
  const author = (message: ThreadMessage) => message.uid === detail?.ownerUid ? "요청자" : message.uid === uid ? "나" : uidLabel(message.uid);
  function renderComment(message: ThreadMessage, nested = false) { const replies = detail?.thread.filter((item) => item.parentId === message.id) ?? []; return <article key={message.id} className={`feed-comment ${message.uid === uid ? "mine" : ""} ${nested ? "nested" : ""}`}><div><span>{author(message)}</span><small>{message.createdAt}</small></div><p>{message.body}</p><button onClick={() => { setReplyTo(message); setReply(""); }}>답글</button>{replies.length > 0 && <div className="nested-comments">{replies.map((item) => renderComment(item, true))}</div>}</article>; }
  return <div className="feed-app"><aside className="feed-rail"><div className="feed-mark"><i /><i /><b /></div><span>SKALA<br />RELAY<br />DESK</span><small>{needCount}<br />NEEDS</small></aside><main>
    <header className="feed-header"><div className="feed-brand">막힘<span>↳</span>교환소 <small>ANON RELAY</small></div><div><p><CircleDot size={13} /> {uid ? `${uidLabel(uid)} · 이 브라우저에만` : "익명 ID 준비 중"}</p><button onClick={() => setComposer(true)}><Plus size={15} /> 요청 올리기</button></div></header>
    <section className="feed-intro"><div><p>SKALA ANONYMOUS DEBUGGING RELAY</p><h1>지금 교환소에<br /><em>{relays.length}개의 막힘</em>이 있어요.</h1><span>정답이 아니라, 먼저 지나가 본 사람의 다음 관점을 찾는 곳.</span></div><div className="feed-stats"><div><b>{needCount}</b><span>도움이 필요한 요청</span></div><div><b>{relays.filter((relay) => relay.state === "힌트 도착").length}</b><span>힌트가 도착한 요청</span></div><div><b>{mine.length + joined.length}</b><span>내가 남긴 흔적</span></div></div></section>
    <section className="feed-toolbar"><div className="filter-row">{(["전체", "도움 필요", "힌트 도착", "내 요청", "내가 참여"] as FilterKey[]).map((item) => <button key={item} onClick={() => setFilter(item)} className={filter === item ? "active" : ""}>{item}{item === "도움 필요" && <small>{needCount}</small>}</button>)}</div><div className="feed-controls"><label><Search size={14} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="기술, 과목, 막힌 장면 검색" /></label><div className="sort-row">{(["최신순", "댓글 많은 순", "도움 필요 순"] as SortKey[]).map((item) => <button key={item} onClick={() => setSort(item)} className={sort === item ? "active" : ""}>{item}</button>)}</div></div></section>
    <section className="feed-layout"><div className="request-feed"><div className="feed-caption"><span>REQUEST STREAM</span><b>{visibleRelays.length}개 요청</b></div>{visibleRelays.length ? visibleRelays.map((relay, index) => <button className={`relay-card ${relay.state.replaceAll(" ", "-")}`} key={relay.id} onClick={() => setDetail(relay)}><div className="relay-index">{String(index + 1).padStart(2, "0")}</div><div className="relay-main"><div className="relay-meta"><span>{relay.mode} · {relay.course}</span><span>{relay.createdAt} · {relay.sample ? "연습 요청" : relay.ownerUid === uid ? "내 요청" : uidLabel(relay.ownerUid)}</span></div><h2>{relay.ask}</h2><p><ArrowRight size={13} /> {relay.tried}</p><div className="relay-foot"><b>{relay.state}</b><span><MessageCircleMore size={14} /> 댓글 {relay.thread.length} · {relay.need}</span></div></div><ArrowRight className="open-arrow" size={18} /></button>) : <div className="feed-empty"><Search size={23} /><h3>조건에 맞는 요청이 없어요.</h3><p>다른 필터로 보거나, 지금 막힌 장면을 첫 요청으로 남겨주세요.</p><button onClick={() => { setFilter("전체"); setSearch(""); }}>전체 요청 보기</button></div>}</div>
      <aside className="participation-panel"><div><p>MY RELAY</p><h2>내가 다시 볼<br /><em>대화</em></h2></div>{mine.length || joined.length ? <div className="participation-list">{[...mine, ...joined].slice(0, 5).map((relay) => <button key={relay.id} onClick={() => setDetail(relay)}><span>{relay.ownerUid === uid ? "내 요청" : "내가 댓글 남김"}</span><strong>{relay.ask}</strong><small>{relay.thread.length}개 대화 <ArrowRight size={13} /></small></button>)}</div> : <div className="participation-empty"><Flame size={20} /><p>아직 내 대화가 없어요.</p><span>도움이 필요한 글을 열고 한 줄만 남겨보세요.</span></div>}<div className="feed-evidence"><img src="/manus-storage/quiet-signal-archive-evidence_91b27012.png" alt="주석이 남은 학습 기록" /><p>막힌 장면도<br />다음 사람의 힌트가 됩니다.</p></div></aside></section>
    <footer>막힘 교환소는 답을 모아두는 곳이 아니라, <strong>다음 한 번을 서로 만들어주는 곳</strong>입니다.</footer>
  </main>
  {composer && <div className="overlay"><div className="request-modal"><button className="close" onClick={() => setComposer(false)}><X size={18} /></button><p>익명 요청 · {uid ? uidLabel(uid) : ""}</p><h2>어디에서 멈췄어요?</h2><span>잘 정리하지 않아도 돼요. 막힌 장면 하나와 해본 것 하나면 충분합니다.</span><div className="mode-chooser">{(["강의 끝", "과제 중", "팀 작업"] as Mode[]).map((item) => <button key={item} onClick={() => setMode(item)} className={mode === item ? "active" : ""}>{item}</button>)}</div><input autoFocus value={ask} onChange={(event) => setAsk(event.target.value)} placeholder="예: 요청은 성공인데 화면이 안 바뀌어요" /><Textarea value={tried} onChange={(event) => setTried(event.target.value)} placeholder="여기까지는 해봤어요. (비워도 돼요)" /><div className="need-chips">{["확인 순서 하나만", "범위 어디서 자를지", "결정 기준 하나", "같이 봐줄 사람"].map((item) => <button key={item} onClick={() => setNeed(item)} className={need === item ? "active" : ""}>{item}</button>)}</div><div className="modal-foot"><small>UID와 요청은 이 브라우저 저장소에만 남아요.</small><button onClick={sendRelay}>요청 올리기 <Send size={15} /></button></div></div></div>}
  {detail && <div className="overlay"><div className="thread-modal"><button className="close" onClick={() => setDetail(null)}><X size={18} /></button><div className="detail-top"><span>{detail.mode} · {detail.course} · {detail.tag}</span><b>{detail.state}</b></div><h2>{detail.ask}</h2><div className="requester-line"><UserRound size={14} /> 요청자 {detail.ownerUid === uid ? "나" : detail.sample ? "연습 요청" : uidLabel(detail.ownerUid)} <small>· 이 글 안에서만 같은 사람으로 보여요</small></div><div className="tried-box"><p>여기까지는 해봤어요</p><strong>{detail.tried}</strong></div>{detail.ownerUid === uid ? <div className="owner-controls"><div><p>REQUEST OWNER</p><strong>이 글의 상태는 요청자만 바꿀 수 있어요.</strong></div><div><button className={detail.state === "다시 해보는 중" ? "active" : ""} onClick={() => updateRequestState("다시 해보는 중")}><CheckCircle2 size={14} /> 다시 해볼게요</button><button className={detail.state === "해결 완료" ? "active complete" : "complete"} onClick={() => updateRequestState("해결 완료")}><Check size={14} /> 해결 완료</button></div></div> : <div className="peer-permission"><UsersRound size={15} /><span>동료는 댓글과 답글로만 도울 수 있어요. 상태 전환은 글쓴이에게만 보여요.</span></div>}<div className="comment-head"><div><p>COMMENTS / REPLIES</p><h3>지나가다 한마디만 남겨주세요.</h3></div><span><UsersRound size={14} /> {detail.thread.length}개</span></div><div className="comment-list">{detail.thread.filter((message) => !message.parentId).length ? detail.thread.filter((message) => !message.parentId).map((message) => renderComment(message)) : <div className="comment-empty">아직 첫 댓글이 없어요. 정답 말고, “저는 여기부터 봤어요”면 충분해요.</div>}</div><div className="reply-box">{replyTo && <div className="replying"><ArrowRight size={14} /> <strong>{author(replyTo)}</strong>님에게 답글 <button onClick={() => setReplyTo(null)}>취소</button></div>}<div className="quick-hints"><button onClick={() => setReply("저는 여기부터 확인해봤어요: ")}>저는 여기부터 봤어요</button><button onClick={() => setReply("이건 한 번 확인해봤어요? ")}>이건 확인해봤어요?</button><button onClick={() => setReply("저는 여기서 이렇게 삽질했어요: ")}>저는 여기서 삽질했어요</button></div><Textarea value={reply} onChange={(event) => setReply(event.target.value)} placeholder={replyTo ? "답글을 남겨주세요." : detail.ownerUid === uid ? "진행 상황을 남겨주세요." : "정답 말고, 다음 한 번만 알려주세요."} /><div className="detail-foot"><span>{detail.ownerUid === uid ? "댓글로 진행 상황을 더 남길 수 있어요." : "요청자가 상태를 바꾸면 여기에도 반영돼요."}</span><button className="hint-send" onClick={sendComment}>{replyTo ? "답글 남기기" : "댓글 남기기"} <ArrowRight size={15} /></button></div></div></div></div>}
  {notice && <div className="notice"><Check size={15} /> {notice}</div>}</div>;
}
